M48
; DRILL file {KiCad (6.0.7)} date Mon Sep  5 20:15:17 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-05T20:15:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.1181
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.1969
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.2165
%
G90
G05
T1
X5.681Y-3.897
X5.683Y-4.005
T2
X7.346Y-5.35
T4
X7.306Y-3.787
T3
G00X5.7862Y-3.782
M15
G01X6.0618Y-3.782
M16
G05
T0
M30
